# Generated by Django 4.2.30 on 2026-05-14 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(db_index=True, help_text='候选人ID', max_length=64)),
                ('session_id', models.CharField(db_index=True, help_text='会话ID', max_length=64, unique=True)),
                ('session_incomplete', models.BooleanField(default=True, help_text='会话是否未完成')),
                ('raw_resume', models.JSONField(default=dict, help_text='原始简历JSON')),
                ('job_config', models.JSONField(default=dict, help_text='岗位配置JSON')),
                ('hard_fields_results', models.JSONField(default=dict, help_text='硬性字段结果')),
                ('project_role_results', models.JSONField(default=dict, help_text='项目角色深度结果')),
                ('profile_data', models.JSONField(default=dict, help_text='完整画像数据')),
                ('confidence_score', models.FloatField(default=0.0, help_text='可信度评分')),
                ('incomplete_reasons', models.JSONField(default=list, help_text='未完成原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '人才画像',
                'verbose_name_plural': '人才画像',
                'db_table': 'ai_talent_profile',
                'indexes': [models.Index(fields=['candidate_id', 'session_id'], name='ai_talent_p_candida_174300_idx')],
            },
        ),
    ]
