# Generated by Django 4.2.30 on 2026-05-25 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_id', models.CharField(db_index=True, help_text='公开访问的配置ID', max_length=32, unique=True)),
                ('job_name', models.CharField(help_text='岗位名称', max_length=256)),
                ('job_description', models.TextField(blank=True, help_text='岗位描述(JD)')),
                ('job_level', models.CharField(default='中级', help_text='岗位级别', max_length=32)),
                ('target_position', models.CharField(help_text='目标职位', max_length=128)),
                ('hard_fields', models.JSONField(default=list, help_text='必问硬性字段列表')),
                ('custom_questions', models.JSONField(default=dict, help_text='自定义问题字典')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', help_text='配置状态', max_length=16)),
                ('expire_at', models.DateTimeField(blank=True, help_text='过期时间', null=True)),
                ('max_interviews', models.IntegerField(default=100, help_text='最大面试人数')),
                ('current_interviews', models.IntegerField(default=0, help_text='当前已面试人数')),
                ('created_by', models.CharField(blank=True, help_text='创建者标识', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '岗位配置',
                'verbose_name_plural': '岗位配置',
                'db_table': 'ai_job_configuration',
                'indexes': [models.Index(fields=['config_id', 'status'], name='ai_job_conf_config__2e2a35_idx'), models.Index(fields=['expire_at'], name='ai_job_conf_expire__142779_idx')],
            },
        ),
    ]
