# Generated by Django 4.2.30 on 2026-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0002_jobconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobconfiguration',
            name='candidate_name',
            field=models.CharField(blank=True, help_text='候选人姓名', max_length=64),
        ),
        migrations.AddField(
            model_name='jobconfiguration',
            name='candidate_phone',
            field=models.CharField(blank=True, help_text='候选人手机号', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobconfiguration',
            name='max_interviews',
            field=models.IntegerField(default=1, help_text='最大面试人数'),
        ),
    ]
