# Generated by Django 4.2.30 on 2026-05-25 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0003_jobconfiguration_candidate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(db_index=True, help_text='候选人唯一标识(姓名_手机号)', max_length=128, unique=True)),
                ('name', models.CharField(help_text='候选人姓名', max_length=64)),
                ('phone', models.CharField(help_text='候选人手机号', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '候选人',
                'verbose_name_plural': '候选人',
                'db_table': 'ai_candidate',
            },
        ),
        migrations.RemoveField(
            model_name='jobconfiguration',
            name='candidate_name',
        ),
        migrations.RemoveField(
            model_name='jobconfiguration',
            name='candidate_phone',
        ),
        migrations.AddField(
            model_name='jobconfiguration',
            name='resume_json',
            field=models.JSONField(blank=True, default=dict, help_text='解析的简历JSON'),
        ),
        migrations.AddField(
            model_name='jobconfiguration',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_configs', to='ai_interview.candidate'),
        ),
    ]
