# Generated by Django 4.2.30 on 2026-05-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0004_candidate_remove_jobconfiguration_candidate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_id',
            field=models.CharField(blank=True, help_text='关联的面试ID', max_length=32, null=True),
        ),
    ]
