# Generated by Django 4.2.30 on 2026-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0005_candidate_interview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='current_round',
            field=models.IntegerField(default=0, help_text='当前轮次'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='dialogue_history',
            field=models.JSONField(default=list, help_text='对话历史记录'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='last_question',
            field=models.TextField(blank=True, help_text='上一个问题'),
        ),
    ]
