# Generated by Django 4.2.30 on 2026-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0006_talentprofile_current_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobconfiguration',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='是否被锁定（有人正在面试）'),
        ),
    ]
