# Generated by Django 4.2.30 on 2026-05-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0007_jobconfiguration_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='interview_completed',
            field=models.BooleanField(default=False, help_text='面试是否已完成（六轮全部结束）'),
        ),
    ]
