# Generated by Django 4.2.30 on 2026-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0008_talentprofile_interview_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='', help_text='候选人邮箱', max_length=128),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(db_index=True, help_text='候选人唯一标识(姓名_邮箱)', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, help_text='候选人手机号', max_length=16, null=True),
        ),
    ]
