# Generated by Django 4.2.30 on 2026-06-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0017_assessmentgroup_is_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='category',
            field=models.CharField(choices=[('resume_parsing', '简历解析'), ('job_match', '简历匹配度'), ('omni_interview', 'Omni语音面试'), ('answer_analysis', '回答分析'), ('feishu_assistant', '飞书')], db_index=True, help_text='Token消耗类别', max_length=32),
        ),
    ]
